version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    volumes:
    - .:/go/src/github.com/yurinohana/ApiServer
    command: 'go run main.go'